
CREATE TABLE state (
    STATE_CODE INT PRIMARY KEY,
    STATE_NAME VARCHAR2(100) NOT NULL,
    STATE_DATE DATE NOT NULL
);

CREATE TABLE city (
    CITY_CODE INT PRIMARY KEY,
    CITY_NAME VARCHAR2(100) NOT NULL,
    CITY_DATE DATE NOT NULL
);

CREATE TABLE COUNTRY (
    CONUNTRY_CODE INT PRIMARY KEY,
    COUNTRY_NAME NOT NULL,
    COUNTRY_DATE DATE NOT NULL
);

CREATE TABLE Employee (
    EMPLOYEE_ID INT PRIMARY KEY,
    STATE_CODE INT REFERENCES state(STATE_CODE),
    COUNTRY_CODE INT REFERENCES country(COUNTRY_CODE),
    CITY_CODE INT REFERENCES city(CITY_CODE),
    MANAGER_ID INT REFERENCES employee(EMPLOYEE_ID),
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    full_name VARCHAR2(201) NOT NULL,
    EMPLOYEE_DATE DATE NOT NULL
);

CREATE TABLE EMPLOYER (
    EMPLOYER_ID INT PRIMARY KEY,
    EMPLOYER_NAME VARCHAR2(100) NOT NULL,
    EMPLOYER_DATE DATE NOT NULL
);

CREATE TABLE HIRING (
    EMPLOYER_ID INT REFERENCES employer(EMPLOYER_ID),
    EMPLOYEE_ID INT REFERENCES employee(employee_id),
    HIRING_DATE DATE NOT NULL,
    CONSTRAINT pk_hiring PRIMARY KEY (employer_id, employee_id)
);

DROP TABLE HIRING;
CREATE TABLE SALARY (
    EMPLOYER_ID INT REFERENCES employer(EMPLOYER_ID),
    EMPLOYEE_ID INT REFERENCES employee(employee_id),
    offer NUMERIC NOT NULL,
    CONTRACT_PERIOD NUMBER NOT NULL,
    OFFER_DATE DATE NOT NULL,
    CONSTRAINT pk_salary PRIMARY KEY (employer_id, employee_id)
);

DROP TABLE employer; -- wouldn't work

